# Generated by Django 3.2.3 on 2021-05-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='Post',
            name='title_tag',
            field=models.CharField(default='My Awesome Blog !!', max_length=255),
        ),
    ]
